version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    hostname: mysqldb
    platform: linux/x86_64
    image: mysql:5.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:3306
    volumes:
      - ./data/:/var/lib/mysql
    networks:
      - node-network

  node_app:
    container_name: node_app
    hostname: node_app
    depends_on:
      - mysqldb
    build: .
    ports:
      - "3000:3000"
    networks:
      - node-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  node-network:
    driver: bridge
